##begin config
version 0.1
residentpri 40
libbase RNGBase
libbasetype struct RNGBase
##end config
##begin cdef
#include <exec/types.h>
##end cdef
##begin cdefprivate
#include "rng_private.h"
##end cdefprivate
##begin functionlist
ULONG RNGRead() ()
##end functionlist
